"""module6_patient_history_and_vitals_triage

Revision ID: 513fe83d6bba
Revises: 252de150cd67
Create Date: 2026-10-03 11:57:28.933347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513fe83d6bba'
down_revision: Union[str, Sequence[str], None] = '252de150cd67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
