"""module4_consultations_prescriptions_lab

Revision ID: e576cccf6a07
Revises: e90b75ef8038
Create Date: 2026-10-03 10:54:10.549480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e576cccf6a07'
down_revision: Union[str, Sequence[str], None] = 'e90b75ef8038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
